name: Dev Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  dev-pipeline-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Run GitLeaks Scan
      #   run: |
      #     wget https://github.com/zricethezav/gitleaks/releases/download/v7.6.0/gitleaks-linux-amd64
      #     chmod +x gitleaks-linux-amd64
      #     ./gitleaks-linux-amd64 -o gitleaks-report.json  

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      # - name: Code Lint Check
      #   run: npm run lint

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.kube_config }}

      - name: Port Forward to SonarQube
        run: |
          kubectl port-forward svc/sonarqube-sonarqube 9000:9000 -n devops &
          # sleep 5 # Give some time for port-forward to start
    
        

      - name: SonarQube Scan
        run: |
          # curl -I http://localhost:9000
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.host.url="http:localhost:9000" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}" \
            -Dsonar.projectKey="pos-api" \
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    

      # - name: Build Docker image
      #   run: docker build -t pos-api .

      - name: Stop Port Forward
        run: |
          pkill -f "kubectl port-forward"                         
